### ISSUE TITLE
Uncaught Exception When Accessing Alert API While Log DB is Down

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#111]
If the log DB (redis) is down, we should fail gracefully, as we do when the Inquisition DB (MySQL) is down.

Request:
```
GET /api/v1/alerts/
```

Response:
```
<br />
<b>Fatal error</b>:  Uncaught Predis\Connection\ConnectionException: Connection refused [tcp://127.0.0.1:6379] in /home/sysadmin/Inquisition/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /home/sysadmin/Inquisition/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection-&gt;onConnectionError('Connection refu...', 111)
#1 /home/sysadmin/Inquisition/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection-&gt;createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4)
#2 /home/sysadmin/Inquisition/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\Parameters))
#3 /home/sysadmin/Inquisition/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection-&gt;createResource()
#4 /home/sysadmin/Inquisition/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\Connec in <b>/home/sysadmin/Inquisition/vendor/predis/predis/src/Connection/AbstractConnection.php</b> on line <b>155</b><br />
```

**Comment by magneticstain** [comment]
This also appears to generate an HTTP 500 error for the Stats API as well.

```
GET /api/v1/stats/
```

**Comment by magneticstain** [comment]
https://github.com/nrk/predis/issues/223
