### ISSUE TITLE
Exception With Requirements Install

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#42]
For Python 3.3 only, when installing the required python packages for running Inquisition on the latest commit, there is an exception when installing scikit:

```
$ pip install -r requirements.txt
Collecting raven (from -r requirements.txt (line 4))
  Downloading raven-6.2.1-py2.py3-none-any.whl (285kB)
    100% |████████████████████████████████| 286kB 2.8MB/s 
Collecting PyMySQL (from -r requirements.txt (line 5))
  Downloading PyMySQL-0.7.11-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 3.7MB/s 
Collecting pygtail (from -r requirements.txt (line 6))
  Downloading pygtail-0.7.0.tar.gz
Collecting redis (from -r requirements.txt (line 7))
  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 4.1MB/s 
Collecting scipy (from -r requirements.txt (line 8))
  Downloading scipy-0.19.1.tar.gz (14.1MB)
    100% |████████████████████████████████| 14.1MB 101kB/s 
Collecting scikit-learn (from -r requirements.txt (line 9))
  Downloading scikit-learn-0.19.0.tar.gz (9.3MB)
    100% |████████████████████████████████| 9.3MB 155kB/s 
Collecting beautifulsoup4 (from -r requirements.txt (line 10))
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 9.4MB/s 
Collecting lxml (from -r requirements.txt (line 11))
  Downloading lxml-4.0.0-cp33-cp33m-manylinux1_x86_64.whl (5.3MB)
    100% |████████████████████████████████| 5.3MB 284kB/s 
Building wheels for collected packages: pygtail, scipy, scikit-learn
  Running setup.py bdist_wheel for pygtail ... done
  Stored in directory: /home/travis/.cache/pip/wheels/ba/27/23/59d879bd451ee06747b28579c00db480b2cc2400e5ad1b6715
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command /home/travis/virtualenv/python3.3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n16bgs/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpxj4t5epip-wheel- --python-tag cp33:
  lapack_opt_info:
  openblas_lapack_info:
    libraries openblas not found in ['/home/travis/virtualenv/python3.3.6/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE
  
  lapack_mkl_info:
  mkl_info:
    libraries mkl,vml,guide not found in ['/home/travis/virtualenv/python3.3.6/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE
  
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries tatlas,tatlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries tatlas,tatlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
    libraries satlas,satlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries satlas,satlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries satlas,satlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
    libraries f77blas,cblas,atlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
    libraries f77blas,cblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries f77blas,cblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE
  
  /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/system_info.py:1548: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    warnings.warn(AtlasNotFoundError.__doc__)
  lapack_info:
    libraries lapack not found in ['/home/travis/virtualenv/python3.3.6/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE
  
  /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/system_info.py:1559: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    warnings.warn(LapackNotFoundError.__doc__)
  lapack_src_info:
    NOT AVAILABLE
  
  /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/system_info.py:1562: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    warnings.warn(LapackSrcNotFoundError.__doc__)
    NOT AVAILABLE
  
  Running from scipy source directory.
  non-existing path in 'scipy/integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-n16bgs/scipy/setup.py", line 416, in <module>
      setup_package()
    File "/tmp/pip-build-n16bgs/scipy/setup.py", line 412, in setup_package
      setup(**metadata)
    File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/tmp/pip-build-n16bgs/scipy/setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
      caller_level = 2)
    File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
      caller_level = caller_level + 1)
    File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy/setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
      caller_level = 2)
    File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
      caller_level = caller_level + 1)
    File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy/linalg/setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
  
  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command /home/travis/virtualenv/python3.3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n16bgs/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
  Failed cleaning build dir for scipy
  Running setup.py bdist_wheel for scikit-learn ... error
  Complete output from command /home/travis/virtualenv/python3.3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n16bgs/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpy0695ypip-wheel- --python-tag cp33:
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "/tmp/pip-build-n16bgs/scikit-learn/setup.py", line 148, in get_scipy_status
      import scipy
  ImportError: No module named 'scipy'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-n16bgs/scikit-learn/setup.py", line 269, in <module>
      setup_package()
    File "/tmp/pip-build-n16bgs/scikit-learn/setup.py", line 259, in setup_package
      .format(scipy_req_str, instructions))
  ImportError: Scientific Python (SciPy) is not installed.
  scikit-learn requires SciPy >= 0.13.3.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
  
  
  ----------------------------------------
  Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Successfully built pygtail
Failed to build scipy scikit-learn
Installing collected packages: raven, PyMySQL, pygtail, redis, scipy, scikit-learn, beautifulsoup4, lxml
  Running setup.py install for scipy ... -error
    Complete output from command /home/travis/virtualenv/python3.3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n16bgs/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-y375d9-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.3.6/include/site/python3.3/scipy:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['/home/travis/virtualenv/python3.3.6/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['/home/travis/virtualenv/python3.3.6/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries satlas,satlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries f77blas,cblas,atlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries lapack_atlas not found in /home/travis/virtualenv/python3.3.6/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/system_info.py:1548: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    lapack_info:
      libraries lapack not found in ['/home/travis/virtualenv/python3.3.6/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/system_info.py:1559: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    lapack_src_info:
      NOT AVAILABLE
    
    /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/system_info.py:1562: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
      NOT AVAILABLE
    
    Running from scipy source directory.
    non-existing path in 'scipy/integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-n16bgs/scipy/setup.py", line 416, in <module>
        setup_package()
      File "/tmp/pip-build-n16bgs/scipy/setup.py", line 412, in setup_package
        setup(**metadata)
      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-n16bgs/scipy/setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
        caller_level = 2)
      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
        caller_level = 2)
      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------
Command "/home/travis/virtualenv/python3.3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n16bgs/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-y375d9-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.3.6/include/site/python3.3/scipy" failed with error code 1 in /tmp/pip-build-n16bgs/scipy/
The command "eval pip install -r requirements.txt " failed. Retrying, 2 of 3.
```

**Comment by magneticstain** [comment]
This SO thread provides the solution:
https://stackoverflow.com/questions/26575587/cant-install-scipy-through-pip

**Comment by magneticstain** [comment]
Turns out support for 3.3 ended a couple days ago. Guess that makes this an easy fix :)

**Comment by magneticstain** [comment]
Fixed with commit https://github.com/magneticstain/Inquisition/commit/d3f8b4a47f3e9bacd79fdcab933deecce9a372a0
