### ISSUE TITLE
Exception Received When Running Inquisition

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#43]
```
Traceback (most recent call last):
  File "/home/josh/Code/Inquisition/inquisition.py", line 172, in <module>
    main()
  File "/home/josh/Code/Inquisition/inquisition.py", line 162, in main
    sage.startNetworkThreatEngine()
  File "/home/josh/Code/Inquisition/lib/destiny/Sage.py", line 121, in startNetworkThreatEngine
    testingData = self.initializeLogData(self.logStore, uniqueFields, 'testing')
  File "/home/josh/Code/Inquisition/lib/destiny/Destiny.py", line 155, in initializeLogData
    raise ValueError('no log data provided for initialization')
ValueError: no log data provided for initialization
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by magneticstain** [comment]
https://sentry.io/carlsonet/inquisition/issues/358580856/

**Comment by magneticstain** [comment]
Issue was no check for empty dataset for raw logs.

Proposed patch in Sage.py @ line 120:
```
# initialize raw logs
                        if self.logStore:
                            self.lgr.debug('initializing log data')
                            testingData = self.initializeLogData(self.logStore, uniqueFields, 'testing')
                            if testingData == None:
                                self.lgr.info('no data after initialization for threat detection - sleeping...')
                            else:
                                self.lgr.debug('making predictions for testing data')
                                predictionResults = self.networkThreatClassifier.predict(testingData)
                                self.lgr.debug('threat detection results :: [ ' + str(predictionResults) + ' ]')
                        else:
                            self.lgr.info('no raw log available for threat detection - sleeping...')
```
