### ISSUE TITLE
Exception When No Host Field Specified

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#45]
An exception is generated by Erudite when there is no record in inquisition.Fields with the 'is_host_field' flag set.
```
$ coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/build.cfg -t
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 154, in startAnomalyDetectionEngine
    hostField = self.getHostFieldName()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 89, in getHostFieldName
    hostFieldName = dbResults['field_name']
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 154, in startAnomalyDetectionEngine
    hostField = self.getHostFieldName()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 89, in getHostFieldName
    hostFieldName = dbResults['field_name']
TypeError: 'NoneType' object is not subscriptable
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 154, in startAnomalyDetectionEngine
    hostField = self.getHostFieldName()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 89, in getHostFieldName
    hostFieldName = dbResults['field_name']
```

**Comment by magneticstain** [comment]
Fixed with commit 
https://github.com/magneticstain/Inquisition/commit/b5286d786e0977937e0d5d7ee0e448b9e468091e
