### ISSUE TITLE
Unit Test Failure w/ Latest Commit

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#46]
Commit https://github.com/magneticstain/Inquisition/commit/b5286d786e0977937e0d5d7ee0e448b9e468091e caused a failure of one unit test after adding the logging->printMatchValues configuration being added.

```
$ coverage run --parallel-mode --source="." -m unittest discover build/tests/
======================================================================
ERROR: test_parseLog_invalidLogTTL (test_parser.ParserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.4.6/lib/python3.4/configparser.py", line 761, in get
    value = d[option]
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/collections/__init__.py", line 805, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/collections/__init__.py", line 797, in __missing__
    raise KeyError(key)
KeyError: 'printmatchvalues'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/magneticstain/Inquisition/build/tests/test_parser.py", line 236, in test_parseLog_invalidLogTTL
    self.parser.parseLog(rawLog='164.169.65.152')
  File "/home/travis/build/magneticstain/Inquisition/lib/anatomize/Parser.py", line 379, in parseLog
    if self.cfg.getboolean('logging', 'printMatchValues'):
  File "/opt/python/3.4.6/lib/python3.4/configparser.py", line 801, in getboolean
    raw=raw, vars=vars)
  File "/opt/python/3.4.6/lib/python3.4/configparser.py", line 775, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/python/3.4.6/lib/python3.4/configparser.py", line 764, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'printmatchvalues' in section: 'logging'
----------------------------------------------------------------------
Ran 28 tests in 0.424s
FAILED (errors=1)
```

**Comment by magneticstain** [comment]
Resolved with commit 
https://github.com/magneticstain/Inquisition/commit/8559a99c163efbf9cacb87c6ae65a41dc6517367
