### ISSUE TITLE
Exception Received for Host Value Parsing During Build

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#47]
```
$ coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/build.cfg -t
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 153, in startAnomalyDetectionEngine
    self.hostStore.append(hostEntry['host_val'])
KeyError: 'host_val'
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 153, in startAnomalyDetectionEngine
    self.hostStore.append(hostEntry['host_val'])
KeyError: 'host_val'
```

**Comment by magneticstain** [comment]
It appears that for some reason, the query is returning data from a previous query:
```
            while True:
                # read in list of already known hosts
                # clear current master host list
                self.hostStore = []

                # fetch fresh host list from inquisition DB
                self.lgr.info('fetching list of already known hosts')
                freshHostStore = self.fetchKnownHostData()
                # traverse through list of host records to add raw host_val entries to master host list
                for hostEntry in freshHostStore:
                    print('HE: ' + str(hostEntry))
                    self.hostStore.append(hostEntry['host_val'])
```

```
$ coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/bad_build.cfg -t || sh -c "exit 0"
HE: {'field_name': 'host'}
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 159, in startAnomalyDetectionEngine
    self.hostStore.append(hostEntry['host_val'])
KeyError: 'host_val'
```

**Comment by magneticstain** [comment]
The data that's being printed is from this function, also in Erudite:
```
    def fetchKnownHostData(self):
        """
        Fetches known host records from inquisition DB and inserts them into the local host store

        :return: dict
        """

        # define sql
        sql = """
                SELECT 
                    host_val 
                FROM 
                    KnownHosts
              """

        # execute query
        with self.inquisitionDbHandle.cursor() as dbCursor:
            dbCursor.execute(sql)

            # fetch results
            hosts = dbCursor.fetchall()

        return hosts
```

**Comment by magneticstain** [comment]
Even weirder, this issue only happens during some calls :/
```
$ coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/bad_build.cfg -t || sh -c "exit 0"
H: ()
H: ()
H: ()
H: ()
H: ()
H: ()
H: ()
H: [{'field_name': 'host'}]
HE: {'field_name': 'host'}
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 159, in startAnomalyDetectionEngine
    self.hostStore.append(hostEntry['host_val'])
KeyError: 'host_val'
H: ()
H: [{'field_name': 'host'}]
HE: {'field_name': 'host'}
Traceback (most recent call last):
  File "inquisition.py", line 172, in <module>
    main()
  File "inquisition.py", line 159, in main
    erudite.startAnomalyDetectionEngine()
  File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 159, in startAnomalyDetectionEngine
    self.hostStore.append(hostEntry['host_val'])
KeyError: 'host_val'
```

**Comment by magneticstain** [comment]
This seems to be either a bug in pymysql or mysql itself, OR mysql running on Travis. I'm not able to reproduce on my local machine, so we'll code around this issue for now unless it's able to be reproduced elsewhere.

**Comment by magneticstain** [comment]
Fixed in commit https://github.com/magneticstain/Inquisition/commit/8fb7a2d1344714abd0fd097724628878ac1dbc72
