### ISSUE TITLE
Build Error When Testing Hazy State Tracking

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#57]
```
$ coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/build_hazy_tracking_enabled.cfg
Traceback (most recent call last):
 File "inquisition.py", line 173, in <module>
/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 InsecureRequestWarning)
 main()
 File "inquisition.py", line 157, in main
 erudite.startAnomalyDetectionEngine()
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 640, in startAnomalyDetectionEngine
 self.performTrafficNodeAnalysis()
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 548, in performTrafficNodeAnalysis
 dstNodeFieldName = self.getFieldNameFromType(typeID=3)
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 111, in getFieldNameFromType
 hostFieldName = dbResults['field_name']
KeyError: 'field_name'
Traceback (most recent call last):
 File "inquisition.py", line 173, in <module>
 main()
 File "inquisition.py", line 157, in main
 erudite.startAnomalyDetectionEngine()
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 640, in startAnomalyDetectionEngine
 self.performTrafficNodeAnalysis()
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 547, in performTrafficNodeAnalysis
 srcNodeFieldName = self.getFieldNameFromType(typeID=2)
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 111, in getFieldNameFromType
 hostFieldName = dbResults['field_name']
KeyError: 'field_name'
Traceback (most recent call last):
 File "inquisition.py", line 173, in <module>
 main()
 File "inquisition.py", line 157, in main
 erudite.startAnomalyDetectionEngine()
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 640, in startAnomalyDetectionEngine
The command "coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/build_hazy_tracking_enabled.cfg" exited with 0.
 self.performTrafficNodeAnalysis()
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 548, in performTrafficNodeAnalysis
 dstNodeFieldName = self.getFieldNameFromType(typeID=3)
 File "/home/travis/build/magneticstain/Inquisition/lib/destiny/Erudite.py", line 111, in getFieldNameFromType
2.35s hostFieldName = dbResults['field_name']
KeyError: 'field_name'
```

**Comment by magneticstain** [comment]
This bug is happening in this function:
```
    def getFieldNameFromType(self, typeID):
        """
        Get name of field to use based on type ID

        :return: str
        """

        hostFieldName = ''

        # define sql
        # DEV NOTE: pymysql seems to have some sort of bug where it only validates strings correctly.
        # If we use %d here, execute will fail even if we explicitly cast typeID as an int.
        sql = """
                SELECT 
                    field_name 
                FROM 
                    Fields 
                WHERE 
                    field_type = %s
                LIMIT 1
            """

        # execute query
        with self.inquisitionDbHandle.cursor() as dbCursor:
            dbCursor.execute(sql, typeID)

            # fetch results
            dbResults = dbCursor.fetchone()
            if dbResults:
                hostFieldName = dbResults['field_name']

        return hostFieldName
```

Adding an IndexError exception catch for field_name should resolve this. Additionally, we should have the records added to the build sql file since these records are expected to be present after installation.

**Comment by magneticstain** [comment]
Changed to:
```
        # get field names associated with each field type
        try:
            srcNodeFieldName = self.getFieldNameFromType(typeID=2)
            dstNodeFieldName = self.getFieldNameFromType(typeID=3)
            self.lgr.debug('using [ ' + str(srcNodeFieldName) + ' ] field as source traffic node and [ '
                           + str(dstNodeFieldName) + ' ] field as destination traffic node')
        except KeyError as e:
            self.lgr.warning('problem while trying to identify field names, skipping traffic analysis  :: [ ' + str(e)
                             + ' ]')
            return
```

**Comment by magneticstain** [comment]
Fixed with commit https://github.com/magneticstain/Inquisition/commit/61dcc0e57aa11c20c4d30a6dc861489664dd88c2

```
$ coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/build_hazy_tracking_enabled.cfg
/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
The command "coverage run --parallel-mode --source="." inquisition.py -c build/src/conf/build_hazy_tracking_enabled.cfg" exited with 0.
```

**Comment by magneticstain** [comment]
Completed with commit https://github.com/magneticstain/Inquisition/commit/3c59315d8ebcdbef39e6d62c31f1eecd0710e203
