### ISSUE TITLE
New Build Failing With ValueError Exception

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#60]
```
1.42s$ coverage run --parallel-mode --source="." -m unittest discover build/tests/
............................Exception ignored in: <bound method Pygtail.__del__ of <pygtail.core.Pygtail object at 0x7f1bb88809b0>>
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pygtail/core.py", line 91, in __del__
    if self._filehandle():
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pygtail/core.py", line 173, in _filehandle
    self._fh = open(filename, "r", 1)
PermissionError: [Errno 13] Permission denied: '/var/log/inaccessible_test_log'
.Exception ignored in: <bound method Pygtail.__del__ of <pygtail.core.Pygtail object at 0x7f1bb8d64400>>
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pygtail/core.py", line 91, in __del__
    if self._filehandle():
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pygtail/core.py", line 173, in _filehandle
    self._fh = open(filename, "r", 1)
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/non_existant_file'
....E........
======================================================================
ERROR: test_processLog (test_parser.ParserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/magneticstain/Inquisition/build/tests/test_parser.py", line 255, in test_processLog
    self.assertTrue(self.parser.processLog('raw log'))
  File "/home/travis/build/magneticstain/Inquisition/lib/anatomize/Parser.py", line 449, in processLog
    , self.stats['total_logs_processed'])
  File "/home/travis/build/magneticstain/Inquisition/lib/anatomize/Parser.py", line 202, in avgStat
    + str(numValsInSet) + ' ]')
ValueError: invalid value provided for number of values in set when calculating stat avg :: [ 0 ]
----------------------------------------------------------------------
Ran 42 tests in 0.484s
FAILED (errors=1)
The command "coverage run --parallel-mode --source="." -m unittest discover build/tests/" exited with 1.
```

**Comment by magneticstain** [comment]
Cause is the change of this line:
```
if numValsInSet < 0:
```
on line 199 of Parser.py in commit https://github.com/magneticstain/Inquisition/commit/d3d36bd116d84c62e565af61d40e28dc6d326cfe was changed to:
```
if numValsInSet < 0:
```

In the test_processLog() unit test, the `total_logs_processed` stat is reset to 0 before running.
```
    def test_processLog(self):
        self.parser.resetParserStats(statType='total_logs_processed')

        self.assertTrue(self.parser.processLog('raw log'))
```

This value is passed to processLog() as `numValsInSet` on line 452 of the same commit:
```
        # get # of chars in log and add to avg
        self.avgStat('average_log_length', self.stats['average_log_length'], len(rawLog)
                     , self.stats['total_logs_processed'])
```

Changing this back to the original value should resolve things.

**Comment by magneticstain** [comment]
Closed with commit https://github.com/magneticstain/Inquisition/commit/3903a39f7ee58cc2aeb885d0077e35daa0e8e245
