### ISSUE TITLE
fork() Does Not Occur During Run Tests

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/Inquisition#69]
When performing run tests in travis CI, the processes are not being forked. This results in reduced test coverage of the logic performed after fork() runs, confirmed by reviewing Coveralls results.

**Comment by magneticstain** [comment]
I suspect this is due to limitations with Travis CI in order to prevent fork bombs.

What we'll do to fix this is check to see if the test_run CLI flag is set, and if so, continue running the contained logic.

**Comment by magneticstain** [comment]
Found this exception when running coverage tests:
```
Traceback (most recent call last):
  File "inquisition.py", line 173, in <module>
    main()
  File "inquisition.py", line 150, in main
    anatomize.startAnatomizer()
  File "/home/travis/build/magneticstain/Inquisition/lib/anatomize/Anatomize.py", line 150, in startAnatomizer
    numLogsBetweenTrackingUpdate=numLogsBetweenTrackingUpdate)
  File "/home/travis/build/magneticstain/Inquisition/lib/anatomize/Parser.py", line 523, in pollLogFile
    every_n=numLogsBetweenTrackingUpdate):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pygtail/core.py", line 81, in __init__
    [int(line.strip()) for line in offset_fh]
ValueError: need more than 0 values to unpack
```

I found another bug in my last commit where new process spawn even when in test mode. I fixed that, and now it seems that it has fixed this exception as well.

Still not sure how, but I suspect it's some sort of race condition between parser processes. Fixing this so that all logic runs in a single process during test mode has resolved it during local testing.

**Comment by magneticstain** [comment]
https://sentry.io/carlsonet/inquisition/issues/410604874/

**Comment by magneticstain** [comment]
https://sentry.io/carlsonet/inquisition/issues/410604750/
